/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;

public class UserToXmlTest {

    @Test
    public void testObjectSerialization() {
        User user = new User();
        user.setUsername("admin");
        user.setPassword("strong");
        StringWriter sw = new StringWriter();
        try {
            JAXBContext jaxbContext = JAXBContext.newInstance(User.class);
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
            jaxbMarshaller.marshal(user, sw);
        } catch (JAXBException e) {
            e.printStackTrace();
        }
        assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><user><password>strong</password><username>admin</username></user>", sw.toString());
    }


    @Test
    public void testParsingXml() {
        User expectedUser = new User();
        expectedUser.setUsername("admin");
        expectedUser.setPassword("strong");
        User user =  null;
        try {
            StringReader reader = new StringReader("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><user><password>strong</password><username>admin</username></user>");
            JAXBContext jaxbContext = JAXBContext.newInstance(User.class);
            Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
            user = (User) jaxbUnmarshaller.unmarshal(reader);

        } catch (JAXBException e) {
            e.printStackTrace();
        }
        assertEquals(expectedUser, user);
    }
}
